### DISCUSSION TITLE
Zero-configuration secretless publishing to PyPI

### DISCUSSION THREAD

**Discussion by webknjaz** [aio-libs/.github#25] [Announcements]
$sbj is now in private beta. My publishing action already supports it: from day one — https://github.com/marketplace/actions/pypi-publish#publishing-with-openid-connect.

Now that it's available, I'm going to gradually remove the secrets containing long-living PyPI API tokens and switching over to OIDC that acquires short-lived temporary upload tokens under the hood. This should also include removing the PyPI bot account access from said projects, which I forgot in a few places, originally.

These projects have already been migrated:
- aiohttp
- aiomonitor
- aiomysql
- async-lru
- frozenlist
- multidict
- yarl

cc @Nothing4You @jettify  @Dreamsorcerer @mjpieters @aio-libs/admins

**Comment by Dreamsorcerer** [comment]
Just looking at setting up a new repo, is it the same configuration, but without the `pypi_token` option?

i.e.
```
    - name: Make Release
      uses: aio-libs/create-release@v1.6.6
      with:
        changes_file: CHANGES.rst
        name: project-name
        version_file: project_name/__init__.py
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dist_dir: dist
        fix_issue_regex: "`#(\\d+) <https://github.com/aio-libs/project-name/issues/\\1>`"
        fix_issue_repl: "(#\\1)"
```
